GET http://localhost:8080/
###
GET http://localhost:8080/info/
###
GET http://localhost:8080/recipe/1
###
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "title": "Test8",
  "cookingTime": 30,
  "ingredients": [
    {
      "title": "Test ingredient",
      "number": 1,
      "measure": "piece"
    }
  ],
  "steps": [
    "Step 1",
    "Step 2",
    "Step 3"
  ]
}
###
GET http://localhost:8080/recipe/
###
PUT http://localhost:8080/recipe/1
Content-Type: application/json

{
  "title": "Test4",
  "cookingTime": 60,
  "ingredients": [
    {
      "title": "Test ingredient",
      "number": 1,
      "measure": "piece"
    }
  ],
  "steps": [
    "Step 1",
    "Step 2",
    "Step 3"
  ]
}
###
DELETE http://localhost:8080/recipe/6
